version: '3'
services:
  app:
    build: .
    command: node_modules/.bin/nodemon
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      REDIS_HOST: redis
  redis:
    image: "redis:alpine"
