version: '3'
services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: node_modules/.bin/nodemon
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
